# neutral color scheme that looks great on both light and dark modes 

[colors.primary]
background = '#4A5D78' # '#4A5D78' #354f73
foreground = '#E3EFF4' 

[colors.normal]
black   = '#6D83A3'   # #5e7495 #6D83A3
red     = '#FFA0BE'#'#FF667A'    
green   = '#9BCB8A'    
yellow  = '#FFD966'    
blue    = '#9BD2FB'    
magenta = '#D1B4E9'    
cyan    = '#95E3D9'    
white   = '#C5D5E0'    

[colors.bright]
black   = '#8499B6'  # #8499B6 #6D83A3
red     = '#FFB1CA' #'#FF7690'   
green   = '#A8E5A8'    
yellow  = '#FFE680'    
blue    = '#B3DEFD'    
magenta = '#DECAEF'    
cyan    = '#A9EEE5'    
white   = '#E0EBF0'    

